version: "3.8"
services:
  db:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev
  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  blackfire:
    image: blackfire/blackfire
    container_name: blackfire_docker_symfony
    ports: ["8307"]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
